# Generated by Django 3.0.6 on 2020-08-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200815_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='_type',
            new_name='post_type',
        ),
    ]
